### ISSUE TITLE
AUR git package

### ISSUE THREAD

**Issue by Jokler** [Talinx/jp2a#3]
You have asked me to switch the Arch Linux `jp2a-git` package to your fork because `cslarsen/jp2a` is not maintained anymore.

I would like to keep the package in line with the `jp2a` package because that's what I would expect as a user of `jp2a-git`. Have you asked the maintainer of `jp2a` to update his package too?

**Comment by Talinx** [comment]
Yes, the `jp2a` package already uses this repository; unfortunately the Upstream URL was not changed [here](https://www.archlinux.org/packages/community/x86_64/jp2a/).
(If you want to confirm this, running `jp2a --help` shows this repository as homepage.)

**Comment by Jokler** [comment]
Alright, thanks. What's the difference between the master and the develop branch?

**Comment by Talinx** [comment]
Features are developed in the develop branch and it is merged into master for a new version release.

**Comment by Jokler** [comment]
I have updated the package template to use your develop branch now.
Thanks for informing me!

**Comment by Talinx** [comment]
Great! Thank you!
