### ISSUE TITLE
Compile without doxygen

### ISSUE THREAD

**Issue by Jokler** [Talinx/jp2a#5]
I don't think generating documentation is needed to create the binary in the AUR package `jp2a-git`. Is it possible to disable Doxygen somehow?

**Comment by Talinx** [comment]
You can remove any Doxygen generation by removing the macro from `configure.ac` before running `autoreconf`, for example with:
```
grep -v DX configure.ac > configure.ac.temp
mv configure.ac.temp configure.ac
```
The `DX_INIT_DOXYGEN` macro makes generating Doxygen documentation possible (with `make doxygen doc`). Generating the binary (i.e. `make`) does not create any documentation.

**Comment by Jokler** [comment]
Now I get this:
```
Makefile:891: *** missing separator.  Stop.
```
The `Makefile` contains this at that line:
```
@DX_RULES@
Doxyfile: Doxyfile.in
    $(editdx) $(srcdir)/$@.in > $@.tmp
    mv $@.tmp $@
```

The goal is mainly just that Doxygen is not a build dependency to make building the package faster.

**Comment by Talinx** [comment]
Oh sorry, this is also necessary:
```
grep -v DX Makefile.am > Makefile.am.temp
mv Makefile.am.temp Makefile.am
```
Doxygen is not a build dependency, [autoconf-archive](https://www.archlinux.org/packages/community/any/autoconf-archive/) is. autoconf-archive contains some macros that don't come with autoconf, so I think that's fine just like autoconf is required. (Although it is not optimal that a package is required for building that is not part of base-devel.)

**Comment by Jokler** [comment]
Oh, should I just add `autoconf-archive` as a dependency then since more may break or do you think it is still worth removing the references to Doxygen?

**Comment by Talinx** [comment]
I can't think of more macros from `autoconf-archive` that I would want to use but adding `autoconf-archive` as dependency is future-proof. It's up to you, works either way.

**Comment by Jokler** [comment]
Your grep on `Makefile.am` doesn't seem to change anything.
I guess I'll just add `autoconf-archive` since it seems to be a small package.
